name: Deploy theme to Kinsta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.KINSTA_USER }}
          server: ${{ secrets.KINSTA_HOST }}
          password: ${{ secrets.KINSTA_PASSWORD }}
          port: ${{ secrets.KINSTA_PORT }} # Ensure this secret is set to 22
          local_path: './*' # Uploads everything inside your root folder
          remote_path: ${{ secrets.KINSTA_PATH }}
          # Exclude files you don't want on your production site
          exclude_or_include: |
            .git/
            .github/
            node_modules/
            package.json
            package-lock.json
            composer.json
